application: quranwebservice
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "30d"

handlers:
- url: /apps/(.*\.css)
  mime_type: text/css
  static_files: apps/\1
  upload: apps/(.*\.css)

- url: /apps/(.*\.html)
  mime_type: text/html
  static_files: apps/\1
  upload: apps/(.*\.html)
  expiration: "1h"

- url: /apps/(.*\.ico)
  mime_type: image/x-icon
  static_files: apps/\1
  upload: apps/(.*\.ico)
  expiration: "7d"

- url: /apps/(.*\.js)
  mime_type: text/javascript
  static_files: apps/\1
  upload: apps/(.*\.js)

- url: /apps/(.*\.json)
  mime_type: application/json
  static_files: apps/\1
  upload: apps/(.*\.json)
  expiration: "1h"

- url: /apps/(.*\.m4v)
  mime_type: video/m4v
  static_files: apps/\1
  upload: apps/(.*\.m4v)

- url: /apps/(.*\.mp4)
  mime_type: video/mp4
  static_files: apps/\1
  upload: apps/(.*\.mp4)

- url: /apps/(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: apps/\1
  upload: apps/(.*\.(ogg|oga))

- url: /apps/(.*\.ogv)
  mime_type: video/ogg
  static_files: apps/\1
  upload: apps/(.*\.ogv)

- url: /apps/(.*\.otf)
  mime_type: font/opentype
  static_files: apps/\1
  upload: apps/(.*\.otf)

- url: /apps/(.*\.rss)
  mime_type: application/rss+xml
  static_files: apps/\1
  upload: apps/(.*\.rss)
  expiration: "1h"

- url: /apps/(.*\.(svg|svgz))
  mime_type: image/svg+xml
  static_files: apps/\1
  upload: apps/(.*\.(svg|svgz))

#- url: /apps/images
#  static_dir: apps/images
#  http_headers:
#    content-type: image/svg+xml

- url: /apps/(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: apps/\1
  upload: apps/(.*\.swf)

- url: /apps/(.*\.ttf)
  mime_type: font/truetype
  static_files: apps/\1
  upload: apps/(.*\.ttf)

- url: /apps/(.*\.txt)
  mime_type: text/plain
  static_files: apps/\1
  upload: apps/(.*\.txt)

- url: /apps/(.*\.xml)
  mime_type: application/xml
  static_files: apps/\1
  upload: apps/(.*\.xml)
  expiration: "1h"

- url: /apps/(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: apps/\1
  upload: apps/(.*\.xpi)

# image files
- url: /apps/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: apps/\1
  upload: apps/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /apps/(.*\.(mid|midi|mp3|wav))
  static_files: apps/\1
  upload: apps/(.*\.(mid|midi|mp3|wav))  

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: apps/\1
  upload: apps/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: apps/\1
  upload: apps/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /apps/(.+)/
  static_files: apps/\1/index.html
  upload: apps/(.+)/index.html
  expiration: "15m"

- url: /apps/(.+)
  static_files: apps/\1/index.html
  upload: apps/(.+)/index.html
  expiration: "15m"

# site root
- url: /apps
  static_files: apps/Quran.html
  upload: apps/Quran.html
  expiration: "15m"

# glyphs restful service
- url: /rest/.*
  script: main.application

# remote api
- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin

libraries:
- name: django
  version: latest

- name: jinja2
  version: latest

- name: webapp2
  version: latest

builtins:
- remote_api: on
